### ISSUE TITLE
Move `graphql` to be peer dependency instead of dependency

### ISSUE THREAD

**Issue by dotansimha** [apollostack/graphql-subscriptions#23]
Unable to work with latest Node, now when adding `graphql` and `graphql-subscriptions` as dependencies - I get duplicate of `graphql`:
```
node_modules
     graphql
     graphql-subscriptions
           node_modules
                 graphql
```

Temporary workaround is to remove `graphql` dependency, and then NPM flatten the need for `graphql` and install it under the root `node_modules`.

**Comment by citium** [comment]
not enough, you also need to update the graphql/package.json
to remove the graphql or to move it to devDependencies or else npm will install graphql 0.7.0 again

**Comment by tmeasday** [comment]
Is this ultimately a version mismatch in the version of `graphql`? I would have thought npm would dedupe it?

**Comment by citium** [comment]
npm only deduplicate when the version are the same, otherwise the different version install locally.
the issue is the graphql version you use to write/generate the schema is different to graphql-subscription.

**Comment by tmeasday** [comment]
Right; so is it not a version mismatch?

**Comment by dotansimha** [comment]
Great!! Thanks
