### ISSUE TITLE
Dynamic channel names

### ISSUE THREAD

**Issue by khankuan** [apollostack/graphql-subscriptions#40]
```
newCommentsChannel: {
   filter: comment => comment.repository_name === args.repoFullName,
},
```
Hi, I was wondering about the snippet above, would it scale to a large number of subscriptions? Since each subscription is doing a filter check, that would be o(n). Alternatively, is there a way to declare that variable upfront, for example `newComments_${postId}` as the channel name. Currently, the `setupFunctions` method seems to be mapping each distinct channel. A way to use a pattern would be helpful. Would love to understand more about optimizing subscriptions. Cheers :)

**Comment by davidyaha** [comment]
Hey @khankuan 
Check out my [apollo blog post](https://dev-blog.apollodata.com/graphql-subscriptions-with-redis-pub-sub-f636fc84a0c4#.wpano732h) especially relevant is the last part about dynamic channel names.

**Comment by khankuan** [comment]
Nice! Did not realize there is a followup post. Thanks! :)

**Comment by davidyaha** [comment]
I'll close it then. Reopen if something else comes up, or rather open an issue on graphql-redis-subscriptions.

**Comment by khankuan** [comment]
@davidyaha Thanks for the tip! It is very helpful :) I thought the setup with triggerTransform and channelOptions might be a little confusing, needing to setup in 2 places. The `path` specified could also be error-prone where another dev might call it `scope` or `entity`.


What do you think of something like: 

```
setupFunctions: {
  commentsAdded: (options, {repoName}) => ({
    'comments.added': {
      filter: comment  => repoName === comment.repoName, // optional filter, defaults to null
      transform: (name) => `${name}.${repoName}`, // optional, defaults to `${name}`
    },
  }),
},
```
I felt that it eliminates the need for an extra layer in triggerTransform and the developer has full control and clarity over what is the channel of interest.

**Comment by davidyaha** [comment]
So actually `channelOptions` is a simple object so that the implementing PubSub Engine could use it in whatever way it would like. This trigger transform that makes sense for redis might not make sense for postgresql engine.
And `path` variable on the redis example could be whatever you want, as long as you use that property on the transformTrigger function. 

This is all non opinionated implementation in the spirit of apollo as a project.
I think the next step would be to create a bundling package that has certain triggers for common use cases like create, update, delete operations on each __typename or something of this sort.

**Comment by khankuan** [comment]
Hmm, would it be more flexible if we simply let the pubsub engine define the variable, eg:
```
  setupFunctions: {
    commentAdded: (options, { repoName }) => ([{
        channel: 'newCommentsChannel',
        filter: comment => comment.repository_name === args.repoFullName,
    }, {
        channel: { domain: 'posts', event: 'newComments' },
        filter: comment => comment.repository_name === args.repoFullName,
    },  {
        channel: repoName => `newComments.${repoName}`,
    }]),
  },
```
