### ISSUE TITLE
Merge all queries on each specific subscription

### ISSUE THREAD

**Issue by yachaka** [apollostack/graphql-subscriptions#6]
Hi,

Actually, if I'm not mistaken, for each subscription, when there is new data available the schema of each listener query is executed against the GraphQL Schema. Am I right ?

This seems rather inefficient.
I think it would be doable to merge all listeners query into one, execute it against the schema and then dispatch only the queried data for each listener.

What do you think ?

**Comment by stubailo** [comment]
This might be doable on a per-client or per-user basis, but we definitely can't do this across multiple users by default because of authorization issues.

Can you give a more specific example of a case where it would be more efficient to merge queries?

**Comment by yachaka** [comment]
Oh ! I forgot about user authentification, and more important, I forgot about query batching/caching.
This is easily solved (i.e. the number of hits to database with each separate subscription being run against the schema) by facebook/dataloader.

Thanks for you quick reply !
