### ISSUE TITLE
Add 3rd argument to PubSub subscribe - options

### ISSUE THREAD

**Issue by ShockiTV** [apollostack/graphql-subscriptions#7]
This little change will enable PubSub to access query itself.
Seems to be the necessary step if we want to implement things like subscribing to RethinkDB changefeeds which itself can trigger publish events.
Without this information we can only hardcode some changefeeds without arguments.

Just little change in SubscriptionManager, I am TS disabled, so no PR :-(
``` 
// 3. subscribe and keep the subscription id
            const subsPromise = this.pubsub.subscribe(triggerName, handler, options);
            subsPromise.then(id => this.subscriptions[externalSubscriptionId].push(id));
```

**Comment by helfer** [comment]
Fixed in #11
